#!/usr/bin/env bash

# parametrs

PROJECT_PATH=$1
SCHEME_NAME=$2
CONFIGURATION=$3
PRODUCT_BUNDLE_IDENTIFIER=$4
DEVELOPMENT_TEAM=$5
INFOPLIST_FILE=$6
ARCHIVE_PATH=$7
EXPORT_PATH=$8
EXPORT_OPTIONS_PATH=$9

# const

LOGIN_KEYCHAIN=$HOME/Library/Keychains/login.keychain

# start

echo -e "\033[1;32m Start archiving ... \033[0m"

mkdir $ARCHIVE_PATH
mkdir $EXPORT_PATH

security unlock-keychain -p ciserver $LOGIN_KEYCHAIN

# build
# xcodebuild build -project $PROJECT_PATH -scheme $SCHEME_NAME -configuration $CONFIGURATION DEVELOPMENT_TEAM=$DEVELOPMENT_TEAM PRODUCT_BUNDLE_IDENTIFIER=$PRODUCT_BUNDLE_IDENTIFIER INFOPLIST_FILE=$INFOPLIST_FILE

# archive
xcodebuild archive -project $PROJECT_PATH -scheme $SCHEME_NAME -configuration $CONFIGURATION -archivePath $ARCHIVE_PATH DEVELOPMENT_TEAM=$DEVELOPMENT_TEAM PRODUCT_BUNDLE_IDENTIFIER=$PRODUCT_BUNDLE_IDENTIFIER INFOPLIST_FILE=$INFOPLIST_FILE

# export
xcodebuild -exportArchive -archivePath $ARCHIVE_PATH -exportPath $EXPORT_PATH -exportOptionsPlist $EXPORT_OPTIONS_PATH DEVELOPMENT_TEAM=$DEVELOPMENT_TEAM PRODUCT_BUNDLE_IDENTIFIER=$PRODUCT_BUNDLE_IDENTIFIER INFOPLIST_FILE=$INFOPLIST_FILE
